### PR TITLE
Update database_name to align with plantsdb_setup script

### PR DESCRIPTION
**Pull request by nbellpactat**

### CODE REVIEW

**Comment by nbellpactat** [comment]
I've left the database configuration string alone in favor of the existing [open PR](https://github.com/udacity/nd0044-c2-API-Development-and-Documentation-exercises/pull/3)

**Comment by nbellpactat** [comment]
The models.py file was improperly formatted, none of the class methods were available due to them not being indented into the scope of the class.

**Review by ronny-udacity — APPROVED** [review]

**Comment by ronny-udacity** [comment]
Hi @nbellpactat Thanks for submitting a PR. It seems there's a conflict in the request. Could you resolve it on your end so we can merge it to the master branch? Thank you.

**Comment by UAnjali** [comment]
Hi @nbellpactat,
Thanks for bringing this to our notice. We have changed the file based on your suggestion and PR#8.
Happy learning
Udacity

**Pull request closed without merging**
